#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "input.h"
#include "parser.h"
#include "../Util.h"
char *readfile(char *filename)
{
    FILE *input = fopen(filename, "r"); // Open the file in read
    assert(input != NULL);
    // Get the file size
    fseek(input, 0, SEEK_END); // Go to the end of the file
    int file_size = ftell(input);
    fseek(input, 0, SEEK_SET); // Go back to the beginning of the file
    // Read the file into a buffer
    char *buffer = malloc(file_size + 1);
    fread(buffer, file_size, 1, input);
    // close file after store into buffer
    fclose(input);
    return buffer;
}

void build_symbol_table(char *buffer, struct symbol_table *table, int file_size)
{
    // set the address of the first line for storge
    int address = 0;
    // the start of the next line
    int line_start = 0;
    for (int i = 0; i < file_size; i++)
    {
        if (buffer[i] == '\n')
        {
            // copy the line into line (don't include '\n')
            char *line = substring(buffer, line_start, i-1);
            // if the last character is ':' then it is a label
            if (line[strlen(line) - 1] == ':')
            {
                // remove the ':' from the label
                line[strlen(line) - 1] = '\0';
                symbol_table_push(table, line, address);
            }
            // set for next line
            line_start = i + 1;
            address += 4;
            free(line);
        }
    }
}

void generate_binary(char *buffer, char *filename, struct symbol_table *table, int file_size)
{
    // read the file for writing
    FILE *output = fopen(filename, "wb");
    assert(output != NULL);
    // set the address of the first line (may be used in branch etc.)
    int address = 0;
    // the start of the next line
    int line_start = 0;
    // store the 32-bit instruction generated by parse
    int *instruction = malloc(sizeof(int));
    for (int i = 0; i < file_size; i++)
    {
        if (buffer[i] == '\n')
        {
            // copy the line into line (don't include '\n')
            char *line = substring(buffer, line_start, i-1);
            parse(line, address, instruction, table);
            // set for next line
            line_start = i + 1;
            address += 4;
            // write instrucion into file
            fwrite(instruction, 4, 1, output);
            free(line);
        }
    }
    free(instruction);
    fclose(output);
}
