#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include "assembles/parser/parse.h"
#include "assembles/parser/input.h"
int main(int argc, char **argv) {
    char *buffer;
    int file_size = readfile(buffer, argv[1]);
    FILE *output = fopen(argv[2], "wb");
    assert(output != NULL);

    // parse each line
    // set the address of the first line (may be used in branch etc.)
    int address = 0;
    // the start of the next line
    int line_start = 0;
    char *line = malloc(sizeof(char));
    // store the 32-bit instruction generated by parse
    int *instruction = malloc(sizeof(int));
    for (int i = 0; i < file_size; i++) {
        if (buffer[i] == '\n') {
            // copy the line into line
            memcpy(line, buffer + line_start, i - line_start);
            line[i - line_start] = '\0';
            parse(line, address, instruction, NULL);
            // set for next line
            line_start = i + 1;
            address += 4;
            // write instrucion into file
            fwrite(instruction, 4, 1, output);
        }
    }
    free(line);
    free(buffer);
    free(instruction);
    fclose(output);
    return EXIT_SUCCESS;
}



